// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeX2kiQrgmN7E2JzKPAM2L1DVo5CpvE2o',
    appId: '1:757189002125:web:80c8a3a83cb11b576073c4',
    messagingSenderId: '757189002125',
    projectId: 'angadi-ssteam',
    authDomain: 'angadi-ssteam.firebaseapp.com',
    storageBucket: 'angadi-ssteam.appspot.com',
    measurementId: 'G-6S5XV114K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbEzjb3lcWrNXjKoCwl3GXA9GPF-vUrvk',
    appId: '1:757189002125:android:2f85d28452e0ea7b6073c4',
    messagingSenderId: '757189002125',
    projectId: 'angadi-ssteam',
    storageBucket: 'angadi-ssteam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtqDj7q6L9JWUEmSpURlTrkPUdVZ8Ouw',
    appId: '1:757189002125:ios:d37c4fda8ef39ab46073c4',
    messagingSenderId: '757189002125',
    projectId: 'angadi-ssteam',
    storageBucket: 'angadi-ssteam.appspot.com',
    iosBundleId: 'com.ssteam.angadi',
  );
}
